apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: twilio-java
  title: Java Twilio Library
  description: A Java library for communicating with the Twilio API and generating TwiML.
  tags: 
    - java
    - sms
    - twilio
  annotations:
    github.com/project-slug: marvin-corea-cvshealth/twilio-java
    backstage.io/techdocs-ref: dir:.
spec:
  type: library
  lifecycle: experimental
  owner: devsecops
  system: twilio
